---
title: "Basic plots"
author: "Tony Fujs"
date: "October 16th, 2014"
output: rmarkdown::tufte_handout
---

```{r, echo = FALSE}
load('./data/data.Rdata')
library(ggplot2)
library(ggthemes)
library(knitr)
opts_chunk$set(cache=TRUE, warning = FALSE, message = FALSE)
```

## Scatter plot: Population vs Stores
```{r, eval=FALSE}
ggplot(
  aes(x = XXXX, y = XXXX),
  data = summary2005) +
  geom_point()
```

```{r, echo = FALSE, fig.margin = TRUE, fig.cap = "Population vs Stores"}
ggplot(aes(x = population, y = stores), data = summary2005) + geom_point() + theme_few()
```
.   
.   
.   
.   
.   
.   
.     
## Scatter Plot: Add regression line
```{r, eval=FALSE}
ggplot(
  aes(x = population, y = stores), 
  data = summary2005) +
  geom_point() +
  geom_XXXX()
```

```{r, echo = FALSE, fig.margin = TRUE, fig.cap = "Population vs Stores"}
ggplot(aes(x = population, y = stores), data = summary2005) + geom_point() + geom_smooth() + theme_few()
```
    
.   
.   
.   
.   
.   
.   
.    
## Bubble plot: Bubble size represents market_share
```{r, eval=FALSE}
ggplot(data = summary2005) +
geom_point(aes(
        x = population,
        y = stores,
        XXXX = market_share))
```

```{r, echo = FALSE, fig.margin = TRUE, fig.cap = "Bubble plot"}
# Bubbles represent market_share 
ggplot(data = summary2005) + geom_point(aes(x = population, y = stores, size = market_share)) + theme_few()
```
.   
.   
.   
.   
.   
.   
.  
## Update the code so each bar represents the total population of the US for each year
```{r, eval=FALSE}
ggplot(
aes(x = factor(year),
    y = population),
data = summary95_05) +
geom_bar(stat = 'identity',
         position = 'identity')
```

```{r, echo = FALSE, fig.margin = TRUE, fig.cap = ""}
ggplot(aes(x = factor(year), y = population), data = summary95_05) +
  geom_bar(stat = 'identity', position = 'stack') + theme_few()
```
.   
.   
.   
.   
.   
.   
.          
## Fix the code below to produce this plot
```{r, eval=FALSE}
ggplot(aes(x = year, y = stores), data = summary) +
  geom_line()
```

```{r, echo = FALSE, fig.margin = TRUE, fig.cap = ""}
ggplot(aes(x = year, y = stores, group = state), data = summary) +
  geom_line() + theme_few()
```
.   
.   
.   
.   
.   
.   
.                
## Edit code to change lines color depending on state
```{r, eval=FALSE}
ggplot(aes(x = year, y = stores, group = state), data = summary) +
  geom_line()
```

```{r, echo = FALSE, fig.margin = TRUE, fig.cap = ""}
ggplot(aes(x = year, y = stores, group = state, color = state), data = summary) +
  geom_line() + theme_few()
```
.   
.   
.   
.   
.   
.   
.         
## Edit the code to produce the following small multiple
```{r, eval=FALSE}
ggplot(aes(x = year, y = stores, group = state, color = state), data = summary) +
  geom_line()
```

```{r, echo = FALSE, fig.margin = TRUE, fig.cap = ""}
ggplot(aes(x = year, y = stores, group = state, color = state), data = summary) +
  geom_line() + facet_wrap(~state) + theme_few()
```
.   
.   
.   
.   
.   
.   
.            
[^tufte_latex]: https://code.google.com/p/tufte-latex/
[^books_be]: http://www.edwardtufte.com/tufte/books_be










